export const CONFIG = {
  API_ENDPOINT: import.meta.env.VITE_API_ENDPOINT as string,
  IPFS_GATEWAY: import.meta.env.VITE_IPFS_GATEWAY as string,
  WIDTH: 32,
  TRAIL_LENGTH: 10,
  DEVICES: 100,
  DEVICE_SPACING: 120,
  PARTICLES_PER_EDGE: 10,
  DEVICE_SIZE: 60,

  REPULSE_RADIUS: 85,
  REPULSE_FORCE: 90,
  RETURN_FORCE: 4,
  NOISE_FORCE: 6,
};
export const PARTICLES_PER_DEVICE = CONFIG.PARTICLES_PER_EDGE ** 3;
export const TOTAL_PARTICLES = CONFIG.DEVICES * PARTICLES_PER_DEVICE;
