version: "3.7"
services:
  yolo-watcher:
    container_name: yolo-watcher
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ipc: host
    restart: unless-stopped
    volumes:
      - ./yolo_input:/yolo_input
      - ./yolo_output:/yolo_output

    environment:
      - YOLO_INPUT_DIR=/yolo_input
      - YOLO_OUTPUT_DIR=/yolo_output

  pinata-publisher:
    build:
      context: .
      dockerfile: Dockerfile.uploader
    restart: unless-stopped
    environment:
      JWT: ${JWT}
      GATE: ${GATE}
      PRED_DIR: /yolo_output
      OUT_DIR: /logs
    volumes:
      - ./yolo_output:/yolo_output
      - ./logs:/logs
