FROM node:22-slim
WORKDIR /app
ENV NODE_ENV=production
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates && rm -rf /var/lib/apt/lists/*

COPY /uploader/package.json ./
RUN npm i --omit=dev

COPY /uploader/index.mjs ./

ENV PRED_DIR=/yolo_output
ENV OUT_DIR=/logs

CMD ["npm", "start"]